---
  extends: airbnb
  env:
    browser: true
  rules:
    comma-dangle: [2, never]
    eol-last: [0]
    no-use-before-define: [2, {functions: false, classes: false}]
    space-before-function-paren: 0
    no-underscore-dangle: 0
    spaced-comment: 0

